### ISSUE TITLE
About the pre-trained model of FreeSeg.

### ISSUE THREAD

**Issue by lvyunqiu** [jiaosiyu1999/MAFT#2]
Hi, 

Is you FreeSeg model trained from scratch or just provided by the original paper? I did not find any pre-trained checkpoint from the FreeSeg project.

Thanks!

**Comment by jiaosiyu1999** [comment]
The FreeSeg model is trained from scratch. You can use the [code](https://github.com/jiaosiyu1999/MAFT/blob/a46436d175ad0ee8f3ebffe1196c6648a22f34d9/configs/coco-stuff-164k-156/mask2former_freeseg.yaml#L1) to complete FreeSeg training.

We also provide the pre-trained weights of FreeSeg [here](https://drive.google.com/file/d/1qt50o_4C-MUIHhYYnlbaaf49OMlEI4z3/view).
