### ISSUE TITLE
Propagation of F^{i*}_{cls}.

### ISSUE THREAD

**Issue by zwyang6** [jiaosiyu1999/MAFT#3]
Thanks for your contributions! I am wodering what is the difference between adding Bias(B) in  Eq.(3) of your paper and directly interacting tokens masked by the binary proposals ?  The former method seems more simple yet efficient to me. Could you kindly explain it ?

**Comment by jiaosiyu1999** [comment]
Thank you for your attention. Adding bias and interacting only with foreground tokens are theoretically equivalent. However, in terms of code implementation, the former method of adding bias is easier to implement.
