### ISSUE TITLE
how to use ip-encoder

### ISSUE THREAD

**Issue by Justhuayu** [jiaosiyu1999/MAFT#5]
I want to use IP Encoder, how can I load the pre trained model of this module separately?

**Comment by Justhuayu** [comment]
I would like to replace ViT-B/16 with ViT-L/ 14@336px Do you have a corresponding pt model?

**Comment by jiaosiyu1999** [comment]
The pretrained weights can be found at [MAFT_Vitl.pt](https://drive.google.com/file/d/1qMhc13JEFbNuNFylD4OCxzEHQaaQ4O8g/view?usp=sharing)

And you need to set `start_layers = 16` by `model.visual.transformer.start_layers = 16`
