### ISSUE TITLE
How to generate the foled val in datasets/VOCdevkit/VOC2010

### ISSUE THREAD

**Issue by ziyouzheilu** [jiaosiyu1999/MAFT#9]
When preparing the datasets,it needs run the command:python datasets/prepare_pascal_ctx_full_sem_seg.py.In the 34th line of prepare_pascal_ctx_full_sem_seg.py,it needs voc_dir/val.So how to generate the val folder?Thanks for your answer.

**Comment by vineet2104** [comment]
How did you solve this?

**Comment by ziyouzheilu** [comment]
> How did you solve this?

I think it is a problem of file organization. I moved the txt files under ImageSets/Segmentation to the outer directory.
